export const somniBountyAbi = [
  {
    type: "function",
    name: "totalCounts",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "projectCount", type: "uint256" },
      { name: "incidentCount", type: "uint256" },
      { name: "fixCount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "scanJobCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "nextFixId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "requiredAgentFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "requiredJsonApiFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "requiredAutomationFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "projectBountyTiers",
    stateMutability: "view",
    inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [
      { name: "critical", type: "uint96" },
      { name: "high", type: "uint96" },
      { name: "medium", type: "uint96" },
    ],
  },
  {
    type: "function",
    name: "getProject",
    stateMutability: "view",
    inputs: [{ name: "projectId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "active", type: "bool" },
          { name: "metadataHash", type: "bytes32" },
          { name: "name", type: "string" },
          { name: "description", type: "string" },
          { name: "socialUrl", type: "string" },
          { name: "imageUrl", type: "string" },
          { name: "githubRepo", type: "string" },
          { name: "agentPayoutWallet", type: "address" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getScanJob",
    stateMutability: "view",
    inputs: [{ name: "scanJobId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "projectId", type: "uint256" },
          { name: "sponsor", type: "address" },
          { name: "criticalBounty", type: "uint96" },
          { name: "highBounty", type: "uint96" },
          { name: "mediumBounty", type: "uint96" },
          { name: "requestedAt", type: "uint64" },
          { name: "status", type: "uint8" },
          { name: "incidentId", type: "uint256" },
          { name: "fixId", type: "uint256" },
          { name: "agentFeeReserve", type: "uint256" },
          { name: "candidateSeverity", type: "uint8" },
          { name: "snapshotURI", type: "string" },
          { name: "resultHash", type: "bytes32" },
          { name: "resultURI", type: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getIncident",
    stateMutability: "view",
    inputs: [{ name: "incidentId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "projectId", type: "uint256" },
          { name: "sponsor", type: "address" },
          { name: "reporter", type: "address" },
          { name: "bounty", type: "uint96" },
          { name: "deadline", type: "uint64" },
          { name: "severity", type: "uint8" },
          { name: "status", type: "uint8" },
          { name: "evidenceHash", type: "bytes32" },
          { name: "metadataURI", type: "string" },
          { name: "winningFixId", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getFix",
    stateMutability: "view",
    inputs: [{ name: "fixId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "incidentId", type: "uint256" },
          { name: "fixer", type: "address" },
          { name: "payoutRecipient", type: "address" },
          { name: "proofURI", type: "string" },
          { name: "proofHash", type: "bytes32" },
          { name: "decision", type: "uint8" },
          { name: "scoreBps", type: "uint16" },
          { name: "resultHash", type: "bytes32" },
          { name: "paid", type: "bool" },
          { name: "paidAmount", type: "uint96" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "quoteSetupBountyTiers",
    stateMutability: "view",
    inputs: [
      { name: "critical", type: "uint96" },
      { name: "high", type: "uint96" },
      { name: "medium", type: "uint96" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "registerProject",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      { name: "socialUrl", type: "string" },
      { name: "imageUrl", type: "string" },
      { name: "githubRepo", type: "string" },
      { name: "metadataHash", type: "bytes32" },
      { name: "agentPayoutWallet", type: "address" },
    ],
    outputs: [{ name: "projectId", type: "uint256" }],
  },
  {
    type: "function",
    name: "setupBountyTiers",
    stateMutability: "payable",
    inputs: [
      { name: "projectId", type: "uint256" },
      { name: "critical", type: "uint96" },
      { name: "high", type: "uint96" },
      { name: "medium", type: "uint96" },
    ],
    outputs: [
      { name: "scanJobId", type: "uint256" },
      { name: "requestId", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "submitFix",
    stateMutability: "nonpayable",
    inputs: [
      { name: "incidentId", type: "uint256" },
      { name: "proofURI", type: "string" },
      { name: "proofHash", type: "bytes32" },
    ],
    outputs: [{ name: "fixId", type: "uint256" }],
  },
  {
    type: "function",
    name: "reclaimExpired",
    stateMutability: "nonpayable",
    inputs: [{ name: "incidentId", type: "uint256" }],
    outputs: [],
  },
] as const;
